### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by zhongxiaokui** [bytedance/appshark#16]
![WeChat Image_20221015174554](https://user-images.githubusercontent.com/93589495/195979962-728cb70d-2368-47f5-9eea-814aaf93c72d.png)

kali 运行报错，请问这是什么原因。

**Comment by nkbai** [comment]
应该是内存不足，建议16g以上的内存来扫描。 如果你的app特别复杂， 可能需要专门的服务器来扫描。
