### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by XHSEC01** [bytedance/appshark#17]
![image](https://user-images.githubusercontent.com/27882761/196843947-ed43820f-0cba-4a8f-90ba-e498fcf6a3cc.png)
![2fd5feb69dfb41943c6f9517a9ead1e](https://user-images.githubusercontent.com/27882761/196843995-6d62b23c-4e6d-4b36-9f9e-13eedecd36be.jpg)

**Comment by nkbai** [comment]
`java -jar AppShark-0.1.1-all.jar config/config.json5`正确的格式应该是在config目录之上运行，因为appshark默认是相当于当前目录去查找config下面的的各种文件。
