### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by XHSEC01** [bytedance/appshark#18]
![image](https://user-images.githubusercontent.com/27882761/196852355-23129f84-dccd-4faf-b20c-5ed373b17bb3.png)

**Comment by nkbai** [comment]
把appshark的整个目录下载下来，然后使用`java -jar AppShark-0.1.1-all.jar config/config.json5` 这样的格式，一定不要进入到config目录中执行。

**Comment by XHSEC01** [comment]
可以了

**Comment by XHSEC01** [comment]
但是又出现了这个问题
![f72cc7ae9ab8428397b5cb346a8eb14](https://user-images.githubusercontent.com/27882761/196870621-b3179c7e-917d-4e5c-b754-08839bd0ccff.jpg)

**Comment by nkbai** [comment]
@humiaoxin 这个是正常运行的日志
