### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by xz-zone** [bytedance/appshark#19]
![image](https://user-images.githubusercontent.com/19305748/197315416-2c3be9a7-08e5-498b-9cce-e962e37e6727.png)

**Comment by nkbai** [comment]
请用带-all.jar，没有-all的是不包含依赖的，需要自行解决依赖的jar包

**Comment by xz-zone** [comment]
![image](https://user-images.githubusercontent.com/19305748/197483749-5be54dc9-4391-4b6a-8a17-666c7128e03d.png)

**Comment by nkbai** [comment]
看着像是文件不存在？
