### ISSUE TITLE
能否支持aar、jar文件的扫描？

### ISSUE THREAD

**Issue by shannon2014** [bytedance/appshark#21]
你好，作为一个大型APP的开发者，每次在APP中集成其他非自研的三方SDK(jar和aar)时，总担心这些SDK会存在隐私合规的问题，我尝试利用appShark对这些SDK进行接入前扫描，在initSoot时，我传入了AnalyzeStepByStep.TYPE.AAR,然后编译出新的AppShark-all.jar,，运行时soot报错，截图如下。查阅soot源码，发现其ClassSourceType不支持aar。本人对soot不太熟悉，无法继续深入研究，
请问appShark是否支持直接扫描jar和aar文件，或者能提供一些思路？谢谢
![image](https://user-images.githubusercontent.com/9985710/200466896-f76ed7e5-bfdf-4111-a153-b2df8c3b683a.png)

![image](https://user-images.githubusercontent.com/9985710/200467091-3e0275b0-838a-4b8b-9212-4dfd761d38c4.png)

![image](https://user-images.githubusercontent.com/9985710/200467167-75e7df65-8d4f-4405-89e9-c50a52f76a76.png)

**Comment by nkbai** [comment]
目前暂不支持，建议通过工具将aar，jar转成apk文件再进行扫描。
