### ISSUE TITLE
Running multiple rules and apps

### ISSUE THREAD

**Issue by R3zk0n** [bytedance/appshark#28]
Hi, Thankyou for open sourcing this tool. Its wonderful and I really enjoy how fast it is, i am still learning writing the rules correctly at the moment but the "Tutorial" for path traversal helped alot!

Is it possible to run the engine with multiple rules and apks? I tried to use "Rule1, Rule2" but it appears to error out, maybe something i am missing?

Thankyou!

**Comment by nkbai** [comment]
this is a sample:
```json
{
  //apk to anlayze
  "apkPath": "/Users/bai/dev/tmp/BypassPathTraversal/apk/app-debug.apk",
  //result output directory
  "out": "out",
  "rules": "ContentProviderPathTraversal.json,broadcastIMEI.json",
  "maxPointerAnalyzeTime": 600,
  //print more info about this rule
  "debugRule": "unZipSlip"
}
```

appshark supports multiple rules, but don't support multiple apks at the same time.

**Comment by R3zk0n** [comment]
Ah thankyou, Im trying to write a rule for setResult issue, however I cant seem to get the format correctly, I tried to sign up to the LARK channel but it says its an invalid QR code, is there place to discuss writing rules? :)

**Comment by nkbai** [comment]
> I tried to sign up to the LARK channel but it says its an invalid QR code
Did you scan this qr code with lark?

**Comment by R3zk0n** [comment]
Yes sir!

**Comment by nkbai** [comment]
> Yes sir!

can you show me the error result? 
I just tested it and there is no problem with this QR code.

**Comment by R3zk0n** [comment]
Ah i was scanning in the wrong place! apologies. Closing the ticket :)
