### ISSUE TITLE
config/tools/ApkName.sh 没有文件或者目录

### ISSUE THREAD

**Issue by why080** [bytedance/appshark#29]
在linux服务器，有这个文件， 用命令   chmod  777 ApkName.sh 加了权限
![image](https://user-images.githubusercontent.com/25812714/212230450-ec5a9f8e-7fa7-4a83-9050-622de7025831.png)

**Comment by why080** [comment]
![image](https://user-images.githubusercontent.com/25812714/212232785-0c92a47d-ab8e-4868-9db5-56d57834781f.png)

**Comment by nkbai** [comment]
@MrWhy121238 Can you show me the command line? Did you follow the readme step by step?

**Comment by Riv4ille** [comment]
可能是用的jar包的版本和源码的版本不匹配导致的，直接用gradle构建一下应该就没问题了。
