### ISSUE TITLE
windows上报错

### ISSUE THREAD

**Issue by heiniuniu** [bytedance/appshark#3]
windows上执行java -jar AppShark-0.1-all.jar config/config.json5，报错：%1 不是有效的 Win32 应用程序

**Comment by heiniuniu** [comment]
是 apkPath路径的问题？  路径写的是一个绝对路径：   "apkPath": "D:\\download\\xxxxxxx.apk"

**Comment by kuangyliang** [comment]
me too,same error

**Comment by Jevon101** [comment]
https://github.com/bytedance/appshark/issues/2 有个已经closed的issue不知道是否是相同问题

**Comment by heiniuniu** [comment]
是相同的问题
