### ISSUE TITLE
检测未命中

### ISSUE THREAD

**Issue by LiHongHui6** [bytedance/appshark#34]
配置检测规则为logSerial.json
![image](https://user-images.githubusercontent.com/23067634/217763707-62b24b9e-8e29-461a-9aec-4489769fa254.png)
检测代码为
![image](https://user-images.githubusercontent.com/23067634/217763851-bd4b0f82-6d16-4333-a04a-23fad0011c3e.png)
检测结果未命中
![image](https://user-images.githubusercontent.com/23067634/217764328-0ce10014-fc99-41d7-b742-8778a1f30227.png)

**Comment by nkbai** [comment]
能否提供apk文件呢？这么简单的情况，应该是能扫出来的。

**Comment by LiHongHui6** [comment]
> 能否提供apk文件呢？这么简单的情况，应该是能扫出来的。

[app-debug.apk.zip](https://github.com/bytedance/appshark/files/10780121/app-debug.apk.zip)

**Comment by nkbai** [comment]
field 不支持通配符，可以使用
```
    "source": {
      "Field": [
        "<android.os.Build: java.lang.String SERIAL>"
      ]
    }
```
这个规则有问题。

**Comment by LiHongHui6** [comment]
> <android.os.Build: java.lang.String SERIAL>

可以了，感谢
