### ISSUE TITLE
来自一个强迫症

### ISSUE THREAD

**Issue by firmianay** [bytedance/appshark#42]
大佬好，都说<source,sink,sanitizer>三元组，但在规则文件中偏偏将sanitizer（名词）写成了sanitize（动词）。强迫症难受，如果需要，我可以提交一个PR

**Comment by nkbai** [comment]
目前已经有不少规则文件这么写了，可以改一下编解码部分，sanitizer,sanitize都支持。 这相当于修改用户api，要考虑兼容性。
