### ISSUE TITLE
【报错】%1 不是有效的 Win32 应用程序

### ISSUE THREAD

**Issue by Kevil-hui** [bytedance/appshark#5]
师傅可以提供下解决方案吗

![screenshot-20220909-190351](https://user-images.githubusercontent.com/43275273/189336485-7bb87046-4c08-4d14-9ab6-5d9e6c196d44.png)

**Comment by kuangyliang** [comment]
+1

**Comment by nkbai** [comment]
可以先用WSL来运行，会尽快修复。

**Comment by nkbai** [comment]
https://github.com/bytedance/appshark/commit/f8e5e6be4d642e1655df21b856706052dd912de5 已修复，可以自行编译。
