### ISSUE TITLE
常量字符串做source，能否使用正则匹配？

### ISSUE THREAD

**Issue by 1kuzus** [bytedance/appshark#75]
> 文档里有提到，以下规则：
> ```
> "source": {
> "ConstString": ["path1"]
> }
> ```
> 去匹配
> ```
> String s="path1";
> f(12,"path1");
> ```
> 时，s将成为source，函数f的参数1将成为source。

现在有需求是希望匹配所有的`f("path\d+")`，如`f("path1")`、`f("path123")`，请教下该如何编写rules呢？

**Comment by nkbai** [comment]
"source": {
"ConstString": ["path*"]
}
试试这样呢？

**Comment by 1kuzus** [comment]
可以实现简单的*匹配，相当于正则的(.*?)，感谢

**Comment by 1kuzus** [comment]
可以实现简单的正则匹配，相当于正则的(.*?)。感谢。
